### ISSUE TITLE
Update SwapStatus

### ISSUE THREAD

**Issue by lvaccaro** [breez/breez-sdk-swift#13]
Hey, I am looking into `SwapInfo` interface with  breez-sdk-swift v0.3.8.
Following the [swift interface](https://github.com/breez/breez-sdk-swift/blob/6f493e9fbe2914c028794dcd31ec4cb2a62e0462/Sources/BreezSDK/BreezSDK.swift#L7500C24-L7500C25) , `SwapStatus` enum defines only `initial` and`expired` status. 

On the other hand, in the [udl specification](https://github.com/breez/breez-sdk/blob/64a928f0355d757b74c823a805b46d9f2faa07aa/libs/sdk-bindings/src/breez_sdk.udl#L520) there are 6 states. 

Could you add these states? Not sure if the change is about this repo or the main brees-sdk repo.
Thanks

**Comment by JssDWt** [comment]
That is correct, the SDK version 0.3.9 doesn't have those states yet: https://github.com/breez/breez-sdk/blob/0.3.9/libs/sdk-bindings/src/breez_sdk.udl#L489-L492

We'll be releasing these changes as part of a 0.4.x release, which should be coming shortly. If you want to get started with testing it right away, you could build the swift bindings from the SDK's main branch yourself.

**Comment by lvaccaro** [comment]
fixed in the last rc version, thanks
